boards/urls.py
from django.urls import path

from . import views

app_name = 'boards'
urlpatterns = [
    # home view
    path('', views.IndexView.as_view(), name='index'),
    # project views
    path('new', views.new_project, name='new_project'),
    path('<int:project_id>/delete', views.delete_project, name='delete_project'),
    # feature views
    path('<int:project_id>/features', views.list_feature, name='list_feature'),
    path('<int:project_id>/<int:feature_id>', views.detail_feature, name='detail_feature'),
    path('<int:project_id>/new_feature', views.new_feature, name='new_feature'),
    path('<int:project_id>/<int:feature_id>/delete_feature', views.delete_feature, name='delete_feature'),
    # item views
    path('<int:project_id>/items', views.list_item, name='list_item'),
    path('<int:project_id>/<int:feature_id>/<int:item_id>', views.detail_item, name='detail_item'),
    path('<int:project_id>/<int:feature_id>/new_item', views.new_item, name='new_item'),
    path('<int:project_id>/<int:feature_id>/<int:item_id>/delete_item', views.delete_item, name='delete_item'),
    # task views
    path('<int:project_id>/<int:feature_id>/<int:item_id>/<int:task_id>', views.detail_task, name='detail_task'),
    path('<int:project_id>/<int:feature_id>/<int:item_id>/new_task', views.new_task, name='new_task'),
    path('<int:project_id>/<int:feature_id>/<int:item_id>/<int:task_id>/delete_task', views.delete_task, name='delete_task'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views as user_views

app_name = 'users'
urlpatterns = [
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

worktracker/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('boards.urls')),
]

boards/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

class Role(models.TextChoices):
    ADMIN = 'ADMIN', _('Administrator')
    USER = 'USER', _('Default User')
    READ = 'READ', _('Read Only')

class Status(models.TextChoices):
    NEW = 'NEW'
    ACTIVE = 'ACTIVE'
    CLOSED = 'CLOSED'

class Priority(models.IntegerChoices):
    LOW = 0
    MEDIUM = 1
    HIGH = 2
    HIGHEST = 3

class Type(models.TextChoices):
    STORY = 'STORY'
    BUG = 'BUG'

class User(models.Model):
    # fields
    name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    role = models.CharField(max_length=5, choices=Role.choices, default=Role.USER)

    def __str__(self):
        return self.name

class Project(models.Model):
    # fields
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=500)
    created_date = models.DateField()
    modified_date = models.DateField()

    def __str__(self):
        return self.title

class Feature(models.Model):
    # foreign keys
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='features')
    
    # fields
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=2000)
    created_date = models.DateField()
    modified_date = models.DateField()
    status = models.CharField(max_length=6, choices=Status.choices, default=Status.NEW)

    def __str__(self):
        return self.title

class Item(models.Model):
    # foreign keys
    feature = models.ForeignKey(Feature, on_delete=models.CASCADE, related_name='items')

    # fields
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=2000)
    created_date = models.DateField()
    modified_date = models.DateField()
    priority = models.IntegerField(choices=Priority.choices, default=Priority.LOW)
    status = models.CharField(max_length=6, choices=Status.choices, default=Status.NEW)
    points = models.PositiveIntegerField()
    item_type = models.CharField(max_length=5, choices=Type.choices, default=Type.STORY)

    def __str__(self):
        return self.title

class Task(models.Model):
    # foreign keys
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="tasks")
    
    # fields
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=2000)
    created_date = models.DateField()
    modified_date = models.DateField()
    priority = models.IntegerField(choices=Priority.choices, default=Priority.LOW)
    hours_completed = models.PositiveIntegerField()
    hours_left = models.PositiveIntegerField()
    original_estimate = models.PositiveIntegerField()
    status = models.CharField(max_length=6, choices=Status.choices, default=Status.NEW)

    def __str__(self):
        return self.title

boards/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from .models import Status, Priority, Type

class DeleteForm(forms.Form):
    delete_field = forms.CharField(label="Type DELETE to delete this project",
                                   help_text="WARNING: You will not be able to recover this project once it is deleted!",
                                   required=False)

    def clean_delete_field(self):
        data = self.cleaned_data['delete_field']
        if data != "DELETE":
            raise ValidationError(_('Enter DELETE to delete the project.'))
        return data

class NewProjectForm(forms.Form):
    title_field = forms.CharField(label="Project Title")
    description_field = forms.CharField(label="Project Description")

class NewFeatureForm(forms.Form):
    title_field = forms.CharField(label="Feature Title")
    description_field = forms.CharField(label="Feature Description")
    status_field = forms.ChoiceField(choices=Status.choices, initial=Status.NEW)

class NewItemForm(forms.Form):
    title_field = forms.CharField(label="Item Title")
    description_field = forms.CharField(label="Item Description")
    priority_field = forms.ChoiceField(label="Item Priority", choices=Priority.choices)
    points_field = forms.IntegerField(label="Item Points", min_value=0)
    type_field = forms.ChoiceField(label="Item Type", choices=Type.choices)
    status_field = forms.ChoiceField(label="Item Status", choices=Status.choices, initial=Status.NEW)

boards/views.py
from datetime import datetime
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .forms import DeleteForm, NewProjectForm, NewFeatureForm, NewItemForm
from .models import Project, Feature, Item, Task

class IndexView(generic.ListView):
    template_name = 'boards/index.html'
    context_object_name = 'project_list'

    def get_queryset(self):
        return Project.objects.order_by('created_date')

# class ProjectView(generic.DetailView):
#     model = Project
#     template_name = 'boards/project.html'

@login_required
def new_project(request):
    if request.method == 'POST':
        form = NewProjectForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title_field']
            description = form.cleaned_data['description_field']
            now = datetime.now().date()
            Project(title=title, description=description, created_date=now,
                    modified_date=now).save()
            messages.success(request, f'{title} has been created.')
            return redirect('boards:index')
    else:
        form = NewProjectForm()
    return render(request, 'boards/new_project.html', {'form': form})

@login_required
def delete_project(request, project_id):
    active_project = get_object_or_404(Project, pk=project_id)
    if request.method == 'POST':
        form = DeleteForm(request.POST)
        if form.is_valid():
            title = active_project.title
            active_project.delete()
            messages.success(request, f'{title} has been deleted.')
            return redirect('boards:index')
    else:
        form = DeleteForm()
    return render(request, 'boards/delete_project.html', {'active_project': active_project, 'form': form})

def list_feature(request, project_id):
    active_project = get_object_or_404(Project, pk=project_id)
    return render(request, 'boards/list_feature.html', {'active_project': active_project})

def detail_feature(request, project_id, feature_id):
    active_project = get_object_or_404(Project, pk=project_id)
    active_feature = get_object_or_404(Feature, pk=feature_id)
    return render(request, 'boards/detail_feature.html', {'active_project': active_project, 'active_feature': active_feature})

@login_required
def new_feature(request, project_id):
    active_project = get_object_or_404(Project, pk=project_id)
    if request.method == 'POST':
        form = NewFeatureForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title_field']
            description = form.cleaned_data['description_field']
            now = datetime.now().date()
            Feature(project=active_project, title=title, description=description,
                    created_date=now, modified_date=now).save()
            return HttpResponseRedirect(reverse('boards:list_feature', args=(active_project.id,)))
    else:
        form = NewFeatureForm()
    return render(request, 'boards/new_feature.html', {'form': form, 'active_project': active_project})

@login_required
def delete_feature(request, project_id, feature_id):
    active_feature = get_object_or_404(Feature, pk=feature_id)
    active_project = get_object_or_404(Project, pk=project_id)
    title = active_feature.title
    active_feature.delete()
    messages.success(request, f'{title} has been deleted.')
    return HttpResponseRedirect(reverse('boards:list_feature', args=(active_project.id,)))

def list_item(request, project_id):
    active_project = get_object_or_404(Project, pk=project_id)
    return render(request, 'boards/list_item.html', {'active_project': active_project})

def detail_item(request, project_id, feature_id, item_id):
    active_project = get_object_or_404(Project, pk=project_id)
    active_feature = get_object_or_404(Feature, pk=feature_id)
    active_item = get_object_or_404(Item, pk=item_id)
    args = {'active_project': active_project, 'active_feature': active_feature,
            'active_item': active_item}
    return render(request, 'boards/detail_item.html', args)

@login_required
def new_item(request, project_id, feature_id):
    active_feature = get_object_or_404(Feature, pk=feature_id)
    active_project = get_object_or_404(Project, pk=project_id)
    if request.method == 'POST':
        form = NewItemForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title_field']
            description = form.cleaned_data['description_field']
            priority = form.cleaned_data['priority_field']
            points = form.cleaned_data['points_field']
            now = datetime.now().date()
            Item(feature=active_feature, title=title, description=description,
                 priority=priority, points=points, created_date=now, modified_date=now).save()
            return HttpResponseRedirect(reverse('boards:project', args=(active_project.id,)))
    else:
        form = NewItemForm()
    return render(request, 'boards/new_item.html', {'form': form, 'active_project': active_project})

@login_required
def delete_item(request, project_id, feature_id, item_id):
    return

def detail_task(request, project_id, feature_id, item_id, task_id):
    active_project = get_object_or_404(Project, pk=project_id)
    active_feature = get_object_or_404(Feature, pk=feature_id)
    active_item = get_object_or_404(Item, pk=item_id)
    active_task = get_object_or_404(Task, pk=task_id)
    args = {'active_project': active_project, 'active_feature': active_feature,
            'active_item': active_item, 'active_task': active_task}
    return render(request, 'boards/detail_task.html', args)

@login_required
def new_task(request, project_id, feature_id, item_id):
    return

@login_required
def delete_task(request, project_id, feature_id, item_id, task_id):
    return

boards/templates/boards/delete_project.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-3 pb-2">Are you sure you want to delete {{active_project.title}}?</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group pb-2">
                <button class="btn btn-danger shadow-sm border rounded" type="submit">DELETE</button>
                <button class="btn btn-light shadow-sm border rounded" type="button" onClick="window.location.href='{% url "boards:index" %}';">Cancel</button>
            </div>
        </form>
    </div>
{% endblock %}

boards/templates/boards/detail_feature.html
{% extends "base.html" %}
{% block title %}
    {{project.title}}
{% endblock %}
{% block content %}
    <div class="border-bottom pb-2 mb-3">
        <h2>{{active_project}}</h2>
    </div>
    <div class="row">
        <div class="col-md-6">
            <h4 class="pb-2 mb-4 text-muted">{{active_feature}}</h4>
        </div>
        <div class="col-md-6 text-right">
            <div class="btn-group">
                <form action="{% url 'boards:new_item' active_project.id active_feature.id %}">
                    <input type="submit" value="Edit" class="btn btn-light border shadow-sm rounded">
                </form>
                <button type="button" class="ml-2 btn btn-danger shadow-sm" style="border:1px solid darkred" data-toggle="modal" data-target="#deleteModal">
                    Delete
                </button>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 border-right">
            {{active_feature.description}}
        </div>
        <div class="col-md-6">
            <p><span class="font-weight-bold"> Status: </span>{{active_feature.status}}</p>
            <p><span class="font-weight-bold"> Created On: </span>{{active_feature.created_date}}</p>
            <p><span class="font-weight-bold"> Last Modified On: </span>{{active_feature.modified_date}}</p>
        </div>
    </div>
    {% comment %} <ul>
        <li>{{active_feature.description}}</li>
        <li>{{active_feature.status}}</li>
        <li>{{active_feature.created_date}}</li>
        <li>{{active_feature.modified_date}}</li>
    </ul> {% endcomment %}
    <div class="row mt-4">
        <div class="col-md-6">
            <h5 class="pb-2 mt-4">Work Items</h5>
        </div>
        <div class="col-md-6 text-right">
            <form action="{% url 'boards:new_item' active_project.id active_feature.id %}">
                <input type="submit" value="+ New Item" class="btn btn-light border shadow-sm rounded">
            </form>
        </div>
    </div>
    <table class="table table-sm">
        <thead>
            <tr>
                <th scope="col">id</th>
                <th scope="col">Title</th>
                <th scope="col">Type</th>
                <th scope="col">Status</th>
            </tr>
        </thead>
        <tbody>
            {% for item in active_feature.items.all %}
                <tr>
                    <td>{{item.id}}</td>
                    <td><a href="{% url 'boards:detail_item' active_project.id active_feature.id item.id %}">{{item}}</a></td>
                    <td>{{item.item_type}}</td>
                    <td>{{item.status}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if not active_feature.items.all %}
        <p class="text-center">{{active_feature}} has no items</p>
    {% endif %}

    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Are you sure?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    All items and tasks under this feature will be deleted. This action cannot be undone.
                </div>
                <div class="modal-footer">
                    <div class="btn-group">
                        <form action="{% url 'boards:delete_feature' active_project.id active_feature.id %}">
                            <input type="submit" value="Delete" class="btn btn-danger shadow-sm" style="border:1px solid darkred">
                        </form>
                        <button type="button" class="ml-2 btn btn-light border shadow-sm rounded" data-dismiss="modal">Cancel</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

boards/templates/boards/detail_item.html
{% extends "base.html" %}
{% block title %}
    {{project.title}}
{% endblock %}
{% block content %}
    <ul>
        <li><a href="{% url 'boards:detail_feature' active_project.id active_item.feature.id %}">{{active_item.feature}}</a></li>
        <li>{{active_item.title}}</li>
        <li>{{active_item.description}}</li>
        <li>{{active_item.priority}}</li>
        <li>{{active_item.points}}</li>
        <li>{{active_item.status}}</li>
        <li>{{active_item.created_date}}</li>
        <li>{{active_item.modified_date}}</li>
    </ul>
    {% if active_item.tasks.all %}
        <table class="table table-sm">
            <thead>
                <tr>
                    <th scope="col">id</th>
                    <th scope="col">Title</th>
                    <th scope="col">Status</th>
                </tr>
            </thead>
            <tbody>
                {% for task in active_item.tasks.all %}
                    <tr>
                        <td>{{task.id}}</td>
                        <td><a href="{% url 'boards:detail_task' active_project.id active_item.feature.id active_item.id task.id %}">{{task}}</a></td>
                        <td>{{task.status}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        No tasks under item.
    {% endif %}
{% endblock %}

boards/templates/boards/detail_task.html
{% extends "base.html" %}
{% block title %}
    {{project.title}}
{% endblock %}
{% block content %}
    <ul>
        <li><a href="{% url 'boards:detail_item' active_project.id active_task.item.feature.id active_task.item.id %}">{{active_task.item}}</a></li>
        <li>{{active_task.title}}</li>
        <li>{{active_task.description}}</li>
        <li>{{active_task.priority}}</li>
        <li>{{active_task.hours_completed}}</li>
        <li>{{active_task.hours_left}}</li>
        <li>{{active_task.original_estimate}}</li>
        <li>{{active_task.status}}</li>
        <li>{{active_task.created_date}}</li>
        <li>{{active_task.modified_date}}</li>
    </ul>
{% endblock %}

boards/templates/boards/index.html
{% extends "base.html" %}
{% block title %}
    Projects
{% endblock %}
{% block content %}
    <div class="border-bottom pb-2 mb-4">
        <div class="row">
            <div class="col-md-6">
                <h2>Projects</h2>
            </div>
            <div class="col-md-6 text-right">
                <form action="{% url 'boards:new_project' %}">
                    <input type="submit" value="+ New Project" class="btn btn-light border shadow-sm rounded">
                </form>
            </div>
        </div>
    </div>
    {% if project_list %}
        <div class="row">
        {% for project in project_list %}
            <div class="col-md-4" style="margin-bottom:30px;">
                <div class="card mx-auto shadow p-3 mb-5 bg-white rounded" style="width:300px;height:300px;">
                    <div class="card-body">
                        <a class="project_link" href="{% url 'boards:list_feature' project.id %}">
                            <h4 class="card-title border-bottom pb-3">{{project.title}}</h4>
                        </a>
                        <p class="card-text">{{project.description}}</p>
                        <form class="delete_project" action="{% url 'boards:delete_project' project.id %}" method="get">
                            {% csrf_token %}
                            <input class="btn btn-danger shadow-sm" style="border:1px solid darkred" type="submit" value="X">
                        </form>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    {% else %}
        <p>No projects available</p>
    {% endif %}
{% endblock %}

boards/templates/boards/list_feature.html
{% extends "base.html" %}
{% block title %}
    {{project.title}}
{% endblock %}
{% block content %}
    <div class="border-bottom pb-2 mb-3">
        <h2>{{active_project}}</h2>
    </div>
    <div class="row">
        <div class="col-md-6">
            <h4 class="pb-2 mb-4 text-muted">Features</h4>
        </div>
        <div class="col-md-6 text-right">
            <form action="{% url 'boards:new_feature' active_project.id %}">
                <input type="submit" value="+ New Feature" class="btn btn-light border shadow-sm rounded">
            </form>
        </div>
    </div>
    {% comment %} </div>
    <form action="{% url 'boards:index' %}">
        <input type="submit" value="Back">
    </form> {% endcomment %}
    {% comment %} <form action="{% url 'boards:new_feature' project.id %}">
        <input type="submit" value="New">
    </form> {% endcomment %}
    <table class="table table-sm">
        <thead>
            <tr>
                <th scope="col">id</th>
                <th scope="col">Title</th>
                <th scope="col">Status</th>
            </tr>
        </thead>
        <tbody>
            {% for feature in active_project.features.all %}
                <tr>
                    <td>{{feature.id}}</td>
                    <td><a href="{% url 'boards:detail_feature' active_project.id feature.id %}">{{feature.title}}</a></td>
                    <td>{{feature.status}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if not active_project.features.all%}
        <p class="text-center">{{active_project}} has no features</p>
    {% endif %}
{% endblock %}

boards/templates/boards/list_item.html
{% extends "base.html" %}
{% block title %}
    {{project.title}}
{% endblock %}
{% block content %}
    <form action="{% url 'boards:index' %}">
        <input type="submit" value="Back">
    </form>
    {% comment %} <form action="{% url 'boards:new_feature' project.id %}">
        <input type="submit" value="New">
    </form> {% endcomment %}
    <table class="table table-sm">
        <thead>
            <tr>
                <th scope="col">id</th>
                <th scope="col">Title</th>
                <th scope="col">Type</th>
                <th scope="col">Status</th>
            </tr>
        </thead>
        <tbody>
            {% for feature in active_project.features.all %}
                {% for item in feature.items.all %}
                    <tr>
                        <td>{{item.id}}</td>
                        <td><a href="{% url 'boards:detail_item' active_project.id feature.id item.id %}">{{item}}</a></td>
                        <td>{{item.item_type}}</td>
                        <td>{{item.status}}</td>
                    </tr>
                {% endfor %}
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

boards/templates/boards/new_feature.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-3 pb-2">Create a New Feature for {{active_project}}</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group pb-2">
                <button class="btn btn-light shadow-sm border rounded" type="submit">Create</button>
            </div>
        </form>
    </div>
{% endblock %}

boards/templates/boards/new_item.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-3 pb-2">Create a New Item for {{active_feature}}</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group pb-2">
                <button class="btn btn-light shadow-sm border rounded" type="submit">Create</button>
            </div>
        </form>
    </div>
{% endblock %}

boards/templates/boards/new_project.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-3 pb-2">Create a New Project</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group pb-2">
                <button class="btn btn-light shadow-sm border rounded" type="submit">Create</button>
            </div>
        </form>
    </div>
{% endblock %}

boards/templates/boards/project.html
{% extends "base.html" %}
{% block title %}
    {{project.title}}
{% endblock %}
{% block content %}
    <form action="{% url 'boards:index' %}">
        <input type="submit" value="Back">
    </form>
    {% comment %} <form action="{% url 'boards:new_feature' project.id %}">
        <input type="submit" value="New">
    </form> {% endcomment %}
    <table class="table table-sm">
        <thead>
            <tr>
                <th scope="col">id</th>
                <th scope="col">Title</th>
                <th scope="col">Status</th>
            </tr>
        </thead>
        <tbody>
            {% for feature in project.features.all %}
                <tr>
                    <td>{{feature.id}}</td>
                    <td>{{feature.title}}</td>
                    <td>{{feature.status}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

        {% comment %} <ul>
        {% for feature in project.features.all %}
            <li>{{feature.title}}</li>
            <li>{{feature.description}}</li>
            <li>
                <form action="{% url 'boards:delete_feature' project.id feature.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="delete">
                </form>
                <form action="{% url 'boards:new_item' project.id feature.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="new">
                </form>
            </li>
            <ul>
            {% for item in feature.items.all %}
                <li>{{item.title}}</li>
                <li>{{item.description}}</li>
                <li>
                    <form action="{% url 'boards:delete_feature' project.id feature.id %}" method="post">
                        {% csrf_token %}
                        <input type="submit" value="delete">
                    </form>
                </li>
            {% endfor %}
            </ul>
        {% endfor %}
        </ul>
        
    {% else %}
        <p>No features available</p>
    {% endif %}
{% endblock %} {% endcomment %}